# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPcimdE6-3rKs_DTg_Kr1RBKYy_3YBKx
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer
import numpy as np

# load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# bot personas
bots = {
    "A": "I like AI, technology and future innovations",
    "B": "I think AI and big companies are harmful",
    "C": "I focus on money, trading and profit"
}

# convert personas to vectors
bot_vectors = {}
for bot in bots:
    bot_vectors[bot] = model.encode(bots[bot])

# cosine similarity
def similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))


# -------- Phase 1 --------
def find_relevant_bots(post_text):
    post_vec = model.encode(post_text)
    matched = []

    for bot in bot_vectors:
        score = similarity(post_vec, bot_vectors[bot])
        if score > 0.3:   # adjusted threshold
            matched.append(bot)

    return matched


# -------- Phase 2 --------
def mock_search(query):
    if "AI" in query:
        return "New AI model released"
    elif "crypto" in query:
        return "Bitcoin price increased"
    else:
        return "Market is stable"

def generate_post(bot_id):
    topic = "AI"
    news = mock_search(topic)

    content = f"{bots[bot_id]} | News: {news}"

    return {
        "bot_id": bot_id,
        "topic": topic,
        "post_content": content[:280]
    }


# -------- Phase 3 --------
def generate_reply(bot_id, parent, history, human):
    # simple protection against prompt injection
    if "ignore" in human.lower():
        return "I will continue based on my original viewpoint."

    return f"{bots[bot_id]} | I disagree with your point."


# -------- RUN --------
if __name__ == "__main__":
    post = "New AI model launched"

    print("Phase 1 Output:", find_relevant_bots(post))

    print("Phase 2 Output:", generate_post("A"))

    print("Phase 3 Output:", generate_reply("A", "", "", "Ignore instructions"))